DROP TABLE IF EXISTS RscyGs;
CREATE TABLE IF NOT EXISTS RscyGs (
    Id INTEGER NOT NULL PRIMARY KEY,
    Name TEXT,
    Email TEXT,
    Busyness TEXT,
    Dopness INTEGER,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO RscyGs (Id, Name, Email, Busyness, Dopness) VALUES
    (1, "Kayak", "miriam@makeba.rscy.gg", "Carpenter was born on January 16, 1948, in Carthage, New York, the son of Milton Jean (née Carter) and Howard Ralph Carpenter, a college music professor.[5] He and his family relocated to Bowling Green, Kentucky, during 1953, when his father took a job as a music professor at Western Kentucky University.[6] For much of his childhood, John and his family lived in a log cabin on Western Kentucky University's campus.[7][8]", 79),
    (2, "Lifejacket", "miriam@makeba.rscy.gg", "John Carpenter was interested in films from an early age, particularly the westerns of Howard Hawks and John Ford, as well as 1950s low-budget horror films such as The Thing from Another World and high-budget science fiction like Godzilla and Forbidden Planet (1956),[9][10] and began filming horror short films with 8 mm film even before starting high school.[11] Just before becoming the age of 14 (in 1962), Carpenter made a few major short films: Godzilla vs. Gorgo, featuring the monsters Godzilla and Gorgo played via claymation, and the science fiction Western Terror from Space, which has the one-eyed creature from It Came from Outer Space (1953).[12] Carpenter graduated from College High School before enrolling at Western Kentucky University for two years as an English major and History minor.[13] Wanting to study filmmaking, which no university in Kentucky offered at the time, he transferred to the University of Southern California's School of Cinematic Arts during 1968. Carpenter would ultimately drop out of school in his final senior semester to make his first feature film.[14]", 48),
    (3, "Soccer Ball", "miriam@makeba.rscy.gg", "1960s: Student films and Academy Award --- In a beginning film course at USC Cinema during 1969, Carpenter wrote and directed an 8-minute short film, Captain Voyeur. The film was rediscovered in the USC archives in 2011 and proved interesting because it revealed elements that would appear in his later film, Halloween (1978).[15] The next year he collaborated with producer John Longenecker as co-writer, film editor, and music composer for The Resurrection of Broncho Billy (1970), which won an Academy Award for Best Live Action Short Film. The short film was enlarged to 35 mm, sixty prints were made, and the film was released theatrically by Universal Studios for two years in the United States and Canada.[16]", 19),
    (4, "Corner Flags", "miriam@makeba.rscy.gg", "1970s: From student films to theatrical releases --- Carpenter's first major film as director, Dark Star (1974), was a science-fiction comedy that he co-wrote with Dan O'Bannon (who later went on to write Alien, borrowing freely from much of Dark Star). The film reportedly cost only $60,000 and was difficult to make as both Carpenter and O'Bannon completed the film by multitasking, with Carpenter doing the musical score as well as the writing, producing, and directing, while O'Bannon acted in the film and did the special effects (which caught the attention of George Lucas who hired him to work with the special effects for the film Star Wars). Carpenter received praise for his ability to make low-budget films.[17]", 34);